const CREATE_ARTICLE = 'CREATE_ARTICLES'
const GET_ARTICLES = 'GET_ARTICLES'
const UPDATE_ARTICLE = 'UPDATE_ARTICLES'
const DELETE_ARTICLE = 'DELETE_ARTICLES'

export {
  CREATE_ARTICLE,
  GET_ARTICLES,
  UPDATE_ARTICLE,
  DELETE_ARTICLE
}
